#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 2.7.10

env:
  - DJANGO=1.10.5

install:
  - pip install -r requirements.txt

script:
  - python manage.py test -p *Test.py
